[pytest]

python_files = test_*.py *_test.py *_Test.py
python_classes = Test* *Test
python_functions = test* *_test *_Test

markers =
    order: run tests in the specified order

addopts = 

    --import-mode=importlib
    --html=reports/report.html
    --self-contained-html

    -W ignore::DeprecationWarning

    --capture=no
    #--log-cli-level=INFO

